# Optional configs used by Nextstrain team
# Params for uploads
upload:
  # Upload params for AWS S3
  s3:
    # AWS S3 Bucket with prefix
    dst: 's3://nextstrain-data/files/workflows/dengue'
    # Mapping of files to upload, with key as remote file name and the value
    # the local file path relative to the ingest directory.
    files_to_upload:
      genbank.ndjson.xz: data/genbank.ndjson
      all_sequences.ndjson.xz: data/sequences.ndjson
      metadata_all.tsv.zst: results/metadata_all.tsv
      sequences_all.fasta.zst: results/sequences_all.fasta
      metadata_denv1.tsv.zst: results/metadata_denv1.tsv
      sequences_denv1.fasta.zst: results/sequences_denv1.fasta
      metadata_denv2.tsv.zst: results/metadata_denv2.tsv
      sequences_denv2.fasta.zst: results/sequences_denv2.fasta
      metadata_denv3.tsv.zst: results/metadata_denv3.tsv
      sequences_denv3.fasta.zst: results/sequences_denv3.fasta
      metadata_denv4.tsv.zst: results/metadata_denv4.tsv
      sequences_denv4.fasta.zst: results/sequences_denv4.fasta

    cloudfront_domain: 'data.nextstrain.org'

